environment:
  matrix:
  - julia_version: 1.0
  - julia_version: 1.1
  - julia_version: 1.2
  - julia_version: 1.3
  - julia_version: 1.4
  - julia_version: nightly

platform:
  - x86 # 32-bit
  - x64 # 64-bit

matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly

branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
  - echo "%JL_BUILD_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"

test_script:
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"
  - C:\projects\julia\bin\julia -e "Pkg.dir(\"RationalFunctions\") |> println" > folder.txt
  - set /p TEST_FOLDER=<folder.txt
  - move %TEST_FOLDER%\test\test-plot.png test-plot-win-%PLATFORM%-%JULIA%.png

artifacts:
  path: test-plot-win-$(platform)-$(julia).png
  name: test-plot
  type: png

deploy:
  description: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token:
    secure: +XlrRjXlE8VtzuCxQeVkctOj9XTZhZWtXVb/eHJyGMBvptlK+JUyAcfzz41NXNS1
  artifact: test-plot
  force_update: true
  on:
    appveyor_repo_tag: true
