name = "RationalFunctions"
uuid = "a89fc88f-fc1e-5208-8949-7a3f8ddd21cd"
authors = ["Arda Aytekin <aytekin@kth.se>"]
version = "0.1.1"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
Compat = "≥ 0.8.0"
GR = "≥ 0.19.0"
Plots = "≥ 0.8.2"
Polynomials = "≥ 0.1.2"
julia = "≥ 0.7.0"

[extras]
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[targets]
test = ["GR", "Plots"]
